repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    disableValidationOnInstall: true
    values:
      - namespaceOverride: observability
      - prometheusOperator:
          namespaces: 
            releaseNamespace: true
            additional:
              - kube-system
              - todoapp

  - name: postgresql
    namespace: todoapp
    chart: ../../charts/postgresql
      
  - name: todoapp
    namespace: todoapp
    chart: ../../charts/todoapp
    values:
    - image:
        repository: fadareak1/supermetrics-todo-app #Location of docker image
        tag: "1.0"
    - service:
        port: 80
    - postgres:
        username: myuser
        database: mydatabase
        password: mypassword
        host: postgresql #review


helmDefaults:
  timeout: 900
  wait: true
  force: true
  atomic: true
  cleanupOnFail: true
  kubeContext: supermetrics
