apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app: {{ include "postgresql.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: database
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} #Change hardcoding of values
      protocol: TCP
  selector:
    app: {{ include "postgresql.name" . }}
